router:
  ip: 10.66.0.40
  username: admin
  password: admin123
browser:
  headless: false
  browser_type: chromium
  viewport:
    width: 1920
    height: 1080
  slow_mo: 100
test_settings:
  screenshot_on_failure: true
  video_on_failure: false
  parallel_workers: 1
  retry_failed: 1
report:
  title: 路由器自动化测试报告
  language: zh-CN
  include_screenshots: true
  include_logs: true
